newIssueWelcomeComment: >
  Hello there! 👋 Welcome to FirstTimers! 🚀
  
  Thank you and congrats 🎉 for opening your very first issue in this repo. A maintainer will get back to you shortly!
  Join our discord community:- https://discord.com/invite/QHJ6szbdP6


newPRWelcomeComment: >
  Hello there! 👋 Welcome to FirstTimers! 🚀
  
  Thank you and congrats 🎉 for opening your first pull request. A maintainer will get back to you shortly!
  Join our discord community:- https://discord.com/invite/QHJ6szbdP6
  

firstPRMergeComment: >
  Congrats on merging your first Pull Request! 🎉 All the best for your amazing open source journey ahead.⚡️
